version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.9

        working_directory: ~/repo

        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-

            - run: yarn install
            - run: yarn build

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
    test:
        docker:
            - image: circleci/node:8.9

        working_directory: ~/repo

        steps:
            - checkout
            - run:
                name: Lint
                command: yarn lint
            - run:
                name: Testing
                command: yarn test
    deploy:
        docker:
            - image: circleci/node:8.9

        working_directory: ~/repo
        steps:
            - attach_workspace:
                at: ~/repo
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
            - run:
                name: Publish package
                command: npm publish

workflows:
  version: 2
  build-test-deploy:
    jobs:
        - build
        - test:
            filters:
                tags:
                    ignore: /.*/
        - deploy:
            requires:
                - build
            filters:
                tags:
                    only: /^v.*/
                branches:
                    ignore: /.*/
